{% set name = "pycups" %}
{% set version = "2.0.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pycups-{{ version }}.tar.gz
  sha256: 843e385c1dbf694996ca84ef02a7f30c28376035588f5fbeacd6bae005cf7c8d

build:
  number: 0
  skip: true  # [not linux]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - libcups
  run:
    - python
    - libcups

test:
  imports:
    - cups
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/zdohnal/pycups
  summary: Python bindings for libcups
  license: GPL-2.0-only
  license_file: COPYING

extra:
  recipe-maintainers:
    - izahn
